kind: pipeline
type: docker
name: caddy-reload

steps:
  - name: validate
    image: caddy:latest
    commands:
      - caddy validate --config Caddyfile

  - name: deploy
    image: caddy:latest
    volumes:
      - /etc/caddy:/etc/caddy
    commands:
      - cp Caddyfile /etc/caddy/Caddyfile
      - caddy reload --config /etc/caddy/Caddyfile

trigger:
  branch:
    - main
