kind: pipeline
type: docker
name: caddy-reload

steps:
  - name: validate
    image: caddy:latest
    pull: never
    commands:
      - caddy validate --config Caddyfile

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 127.0.0.1
      port: 32179
      username: root
      key:
        from_secret: SSH_KEY
      script:
        - cd /opt/drone/repos/veryos/caddy-config && cp Caddyfile /etc/caddy/Caddyfile
        - caddy reload --config /etc/caddy/Caddyfile

trigger:
  branch:
    - main
