kind: pipeline
type: docker
name: caddy-reload

steps:
  - name: validate
    image: caddy:latest
    pull: never
    commands:
      - caddy validate --config Caddyfile

  - name: deploy
    image: caddy:latest
    pull: never
    volumes:
      - name: caddy-config
        path: /etc/caddy
    commands:
      - cp Caddyfile /etc/caddy/Caddyfile
      - caddy reload --config /etc/caddy/Caddyfile

volumes:
  - name: caddy-config
    host:
      path: /etc/caddy

trigger:
  branch:
    - main
